### PR TITLE
Implement entries visible

### LINKED ISSUE #156: Implement entriesVisible handling
* [ ] all entries are visible when `entriesVisible=true`
* [ ] only selected entries are visible when template is unknown
* [ ] only selected entries are visible for any other value:
  * [ ] name
  * [ ] id
  * [ ] process properties (id, name)
  * [ ] templates-specific entries

### PR DESCRIPTION
**Pull request by barmac**
Closes #156 

Built on top of https://github.com/bpmn-io/bpmn-properties-panel/pull/160

### CODE REVIEW

**Comment by barmac** [comment]
Converting this to draft due to a requirement I just added to #156:
> only selected entries are visible when template is unknown

This is how it works in the old properties panel.

**Comment by barmac** [comment]
Ready for review again.

**Comment by MaxTru** [comment]
Would it be possible to get a custom artifact to test this?

**Comment by barmac** [comment]
The links are now active.

**Comment by MaxTru** [comment]
One bug I found during testing: https://github.com/bpmn-io/bpmn-properties-panel/issues/165

**Review by MaxTru — CHANGES_REQUESTED** [review]
Two things (next to the seperate issues I created)

**1) Default renderings disappear when variable assignments are switched off:**
defaultRenderings

**2) I cannot change some properties via template logic when setting them to undefined?**

1. Have this template and apply it to a serviceTask:
```
{
    "$schema": "https://unpkg.com/@camunda/element-templates-json-schema@0.4.0/resources/schema.json",
    "name": "External Service Task (with Errors)",
    "id": "com.camunda.example.ExternalServiceTaskWithErrors",
    "appliesTo": [
      "bpmn:ServiceTask"
    ],
    "properties": [
      {
        "binding": {
          "name": "camunda:type",
          "type": "property"
        },
        "type": "Hidden",
        "value": "external"
      },
      {
        "binding": {
          "name": "camunda:topic",
          "type": "property"
        },
        "label": "External Task Topic",
        "type": "String",
        "value": "task-topic"
      },
      {
        "value": "expression-value",
        "label": "Error Expression",
        "type": "String",
        "binding": {
          "type": "camunda:errorEventDefinition",
          "errorRef": "Error_1"
        }
      }
    ],
    "scopes": [
      {
        "type": "bpmn:Error",
        "id": "Error_1",
        "properties": [
          {
            "value": "error-code",
            "label": "Error Code",
            "binding": {
              "type": "property",
              "name": "errorCode"
            }
          },
          {
            "value": "error-message",
            "label": "Error Message",
            "binding": {
              "type": "property",
              "name": "camunda:errorMessage"
            }
          },
          {
            "value": "error-name",
            "label": "Error Name",
            "binding": {
              "type": "property",
              "name": "name"
            }
          }
        ]
      }
    ]
  }
```
2. Set the topic to blank (``)
3. Notice that t
etBug2
he change does not have effect on XML

**Comment by barmac** [comment]
> Default renderings disappear when variable assignments are switched off

I think I know what the reason is. When the toggle is switched off, we remove the parameter. Then, as it is not present in the inputOutput, we don't replace it with a custom entry.

**Comment by barmac** [comment]
The input/output works fine on `main` so it's just a bug in this PR.

**Comment by barmac** [comment]
Added a fix for a missing output name: https://github.com/bpmn-io/bpmn-properties-panel/pull/161/commits/bebd803db583ce3a7b2e5baee7da434f4f08c6a0 Note that it's broken in the old properties panel too.

Ready for re-review.

**Comment by barmac** [comment]
I've triggered [another build](https://github.com/camunda/camunda-modeler/actions/runs/1462385162) so that the artifacts are up to date.

**Comment by MaxTru** [comment]
> I've triggered [another build](https://github.com/camunda/camunda-modeler/actions/runs/1462385162) so that the artifacts are up to date.

Do you have the links to the artifacts from this build still saved?

**Comment by MaxTru** [comment]
One bug I found during testing:
https://github.com/bpmn-io/bpmn-properties-panel/issues/177

I guess this is not related to this PR? 

Will continue testing at later point in time

**Comment by barmac** [comment]
> I guess this is not related to this PR?

Untreated but necessary to complete the epic. Thanks for the report.

**Review by MaxTru — CHANGES_REQUESTED** [review]
This bug:
image

still exists? Do I miss something?

**Comment by MaxTru** [comment]
(minor) First commit message exceed the usual max length

**Comment by barmac** [comment]
> still exists? Do I miss something?

Did you download the latest artifact? I cannot reproduce it.

https://user-images.githubusercontent.com/28307541/142198419-8f0521d1-a8d4-41f3-8d72-42fbc1df7f10.mov

**Comment by barmac** [comment]
> (minor) First commit message exceeds the usual max length

It should be fine now.

**Comment by MaxTru** [comment]
> > still exists? Do I miss something?
> 
> Did you download the latest artifact? I cannot reproduce it.
> 
>  Screen.Recording.2021-11-17.at.13.12.20.mov

I just downloaded from
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/entries-visible/camunda-modeler-entries-visible-linux-x64.tar.gz

I used this template:
```
{
    "$schema": "https://unpkg.com/@camunda/element-templates-json-schema@0.4.0/resources/schema.json",
    "name": "Default Rendering",
    "id": "com.camunda.example.DefaultRendering",
    "appliesTo": [
      "bpmn:ServiceTask"
    ],
    "properties": [
      {
        "label": "Input Parameter",
        "binding": {
          "type": "camunda:inputParameter",
          "name": "processVar"
        }
      },
      {
        "label": "Output Parameter",
        "binding": {
          "type": "camunda:outputParameter",
          "source": "outputParam"
        }
      }
    ]
  }
```

**Comment by barmac** [comment]
I see. To reproduce it, one needs to disable all of the inputs and outputs.

**Comment by barmac** [comment]
Templates are a complex topic 🤯

**Comment by barmac** [comment]
When we toggle off (=> remove from XML) all of the inputOutput members, the whole InputOutput is removed. Thus, we cannot really "update" the groups as they don't exist anymore.

**Comment by barmac** [comment]
OK I've reimplemented the input/output/errors groups so that it should work now. Please verify it with the new build which I have just triggered.

**Comment by barmac** [comment]
I messed up the build. Rebuilding this right now with the changes I implemented yesterday.

**Comment by MaxTru** [comment]
The particular feature is still broken I think
Peek 2021-11-18 17-07


The rest looks good!

@barmac I would be okay to approve this and create a seperate bug report for this. (It is an edge case...). Maybe this helps to bring this out of the door?

**Comment by barmac** [comment]
@MaxTru I've rebased this branch on https://github.com/bpmn-io/bpmn-properties-panel/pull/185 and cannot reproduce the issue you shared in the browser. However, I can reproduce it in the build artifact. I suspect this is because of some behaviour in the Modeler 🤷

**Comment by barmac** [comment]
I bet it's this component and then it has to be fixed in camunda-bpmn-js: https://github.com/camunda/camunda-bpmn-js/blob/main/lib/camunda-platform/features/modeling/behavior/UpdateInputOutputBehavior.js

**Review by MaxTru — APPROVED** [review]
Approved, 
but also created https://github.com/bpmn-io/bpmn-properties-panel/issues/186 as follow-up

**Pull request merged**
