### PR TITLE
Add template information

### LINKED ISSUE #145: Template information (text)
image

* [ ] Name
* [ ] Version
* [ ] Description
* [ ] Opens/closes
* [ ] [Looks as on the design](https://fluffy-fiesta-212e1c7c.pages.github.io/prototypes/visual-ide/v14/)

### PR DESCRIPTION
**Pull request by barmac**
- test: improve templates example
- feat(element-templates): add template information

Closes #145

Requires https://github.com/bpmn-io/bpmn-properties-panel/pull/146

### CODE REVIEW

**Comment by barmac** [comment]
@andreasgeier @philippfromme @pinussilvestrus Ready for review.

**Comment by barmac** [comment]
Sorry, closed by accident.

**Comment by barmac** [comment]
It breaks on unrelated test 🙈

**Comment by barmac** [comment]
Test via `npm run start:templates`.

**Comment by barmac** [comment]
Feel free to use the artifacts:

- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/template-information/camunda-modeler-template-information-linux-x64.tar.gz
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/template-information/camunda-modeler-template-information-mac.dmg
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/template-information/camunda-modeler-template-information-mac.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/template-information/camunda-modeler-template-information-win-ia32.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/template-information/camunda-modeler-template-information-win-x64.zip

Kudos to @philippfromme for preparing `camunda/camunda-modeler#element-templates` branch 👏

**Comment by andreasgeier** [comment]
We agreed to have a dedicated review with an artifact that contains all template implementations. Therefore, we skip design review for this PR.

**Comment by MaxTru** [comment]
Unrelated, but still an issue:
The `Template` section shows even if there is no matching template. @barmac should I create an issue for that, or is that tackled already somwhere?

Example:
* Select process
Screenshot_20211105_163112
* Have no template at hand
Screenshot_20211105_163132

**Comment by barmac** [comment]
It's not tackled, please create an issue.

**Comment by MaxTru** [comment]
Design-wise this works as intended (also tested with Cawemo):

Screenshot_20211105_163722

**Comment by MaxTru** [comment]
Bug discovered during testing: https://github.com/bpmn-io/bpmn-properties-panel/issues/158

**Review by MaxTru — APPROVED** [review]
Good stuff

**Pull request merged**
