### PR TITLE
Implement camunda:FormData#businessKey for Start Events

### LINKED ISSUE #110: Implement camunda:FormData#businessKey for Start Events
Old properties panel:

image

Expected XML:

```xml
<bpmn:startEvent id="Event_1p925zq">
  <bpmn:extensionElements>
    <camunda:formData businessKey="FormField_1">
      <camunda:formField id="FormField_1" />
    </camunda:formData>
  </bpmn:extensionElements>
</bpmn:startEvent>
```

---

Child of https://github.com/bpmn-io/bpmn-properties-panel/issues/2

### PR DESCRIPTION
**Pull request by philippfromme**
When at least one `camunda:FormField` with a `camunda:id` is configured a `camunda:businessKey` can be set.

image

Updating `camunda:FormData` is handled in https://github.com/camunda/camunda-bpmn-js/pull/47.

Closes #110

### CODE REVIEW

**Comment by MaxTru** [comment]
Is this ready for review?

**Comment by philippfromme** [comment]
> Is this ready for review?

Yes! 👍🏻

**Review by MaxTru — APPROVED** [review]
LGTM!

**Comment by andreasgeier** [comment]
UX feedback:

1. I'm not sure why the business key deserves its own section. I would have expected it to be part of the form section, below the form key. Is it technically easier to control its visibility in its own section or is there another reason for the separation?

2. I would like to change the order of the sections. The basic rule for the order is: from global to specific; or a logical order (b depends on a). In that sense I would prefer this order:
    1. Form
    2. Form fields
    3. Form business key (in case we keep this section)

3. As listed in the example under point 2, I would also like to see the togetherness of these sections reflected in the naming. In the naming that is shown in Philipp's screenshot, it is hard to understand that these properties belong together. And the confusing order strengthens that issue.

_Screenshot that showcases the mentioned expectations:_

<br>

Screen Shot 2021-09-23 at 19 44 36

**Comment by MaxTru** [comment]
> UX feedback:
> 
> 1. I'm not sure why the business key deserves its own section. I would have expected it to be part of the form section, below the form key. Is it technically easier to control its visibility in its own section or is there another reason for the separation?

=> The `FormBusinessKey` is only relevant for `generatedFormData`. Hence putting it in the Forms section makes it even more semantically confusing IMO. Ideally we would put it in the `GeneratedForm` section, but that does not work since it is a list section (we would need to go with nested lists then, and disable the `businessKey` field if no formField was configured, which is also not nice). Therefore IMO this is okay.

> 2. I would like to change the order of the sections. The basic rule for the order is: from global to specific; or a logical order (b depends on a). In that sense I would prefer this order:
>    
>    1. Form
>    2. Form fields
>    3. Form business key (in case we keep this section)

=> Agreed

> 3. As listed in the example under point 2, I would also like to see the togetherness of these sections reflected in the naming. In the naming that is shown in Philipp's screenshot, it is hard to understand that these properties belong together. And the confusing order strengthens that issue.
> 

=> Agreed

**Comment by philippfromme** [comment]
@andreasgeier @MaxTru Reordering the groups makes sense. As Max mentioned, the business key has to go in its own group since it can't be put in the _Generated task form_.

**Comment by philippfromme** [comment]
I've reordered the groups as suggested.

chrome_5iiLcahLEh

**Review by andreasgeier — APPROVED** [review]
I'm not convinced that the togetherness of the groups is clear enough with the current labels. However, we can iterate on that when the properties panel feature set is done. So, greenlight from my side.

**Pull request merged**
