### PR TITLE
Correctly update template

### LINKED ISSUE #165: Update Element Template Feature broken
__Describe the Bug__

Update Element Template Feature broken

__Steps to Reproduce__

ETBug

1. Have multiple templates from Cawemo synced
2. Apply one template
3. => note that even though the template does not have a newer version, one can apply a new version. => the actual template is changed

(It seems the update logic does not filter on template id?)

__Expected Behavior__

Update element template logic only available for template with the same ID (and multiple versions)

__Environment__

https://github.com/bpmn-io/bpmn-properties-panel/pull/161

### PR DESCRIPTION
**Pull request by barmac**
* Display update button only if an update is available.
* Update to the newest version of the template.

Closes #165

### CODE REVIEW

**Comment by barmac** [comment]
Ready for review.

**Comment by MaxTru** [comment]
Artifacts to test this:
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/develop/camunda-modeler-develop-linux-x64.tar.gz
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/develop/camunda-modeler-develop-mac.dmg
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/develop/camunda-modeler-develop-mac.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/develop/camunda-modeler-develop-win-ia32.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/develop/camunda-modeler-develop-win-x64.zip

**Comment by MaxTru** [comment]
I cannot get build-on-demand to build an artifact for this. I think I am lost in complexity (camunda-bpmn-js requires feature branch, which would have a dependecy to this branch here right?)

@barmac could you please help me to build an artifact to test this PR?

**Comment by pinussilvestrus** [comment]
I think what makes more sense is to use [this branch](https://github.com/camunda/camunda-modeler/tree/element-templates) of the Camunda Modeler and use the branch of this PR as dependency in build-on-demand. This skips camunda-bpmn-js as a dependency for the properties panel.

**Comment by pinussilvestrus** [comment]
If artifacts are not needed for this bug fix, this command could also be sufficient

```sh
npx @bpmn-io/sr camunda/camunda-modeler#element-templates -c "npm start" -l "bpmn-io/bpmn-properties-panel#165-fix-update-template-feature"
```

or simply linking `bpmn-io/bpmn-properties-panel` locally in `camunda-modeler/client` with the element branch checked out.

**Comment by MaxTru** [comment]
> If artifacts are not needed for this bug fix, this command could also be sufficient
> 
> ```shell
> npx @bpmn-io/sr camunda/camunda-modeler#element-templates -c "npm run dev" -l "bpmn-io/bpmn-properties-panel#165-fix-update-template-feature"
> ```
> 
> or simply linking `bpmn-io/bpmn-properties-panel` locally in `camunda-modeler/client` with the element templates branch checked out.

<3 for your comments - thanks!

**Comment by MaxTru** [comment]
Artifacts for testing

https://github.com/camunda/camunda-modeler/actions/runs/1440141267

https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/element-templates/camunda-modeler-element-templates-linux-x64.tar.gz
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/element-templates/camunda-modeler-element-templates-mac.dmg
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/element-templates/camunda-modeler-element-templates-mac.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/element-templates/camunda-modeler-element-templates-win-ia32.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/element-templates/camunda-modeler-element-templates-win-x64.zip

**Review by MaxTru — APPROVED** [review]
Works - tested with posted artifacts.

**Comment by pinussilvestrus** [comment]
I discovered a little UI bug, which is not related to this PR: https://github.com/bpmn-io/bpmn-properties-panel/issues/174

**Pull request merged**
