### PR TITLE
chore(CloudProvider): add documentation links for key inputs

### PR DESCRIPTION
**Pull request by MaxTru**
* This is a quick fix as we agreed to better guide the users when
  starting with Cloud
* There are several follow-ups to better implement this:
  1. implement bpmn-io/properties-panel#119 and migrate the links @MaxTru 
  2. develop a concept how to better display help links (e.g., provide
     ability to have documentation for entire sections) @andreasgeier 
  3. better aling docs with propPanel links (DevRel?)

Screenshots of changes:
Screenshot_20211124_161830

Screenshot_20211124_161857

Screenshot_20211124_161918

Screenshot_20211124_161948

Screenshot_20211124_162027

Screenshot_20211124_162048

Screenshot_20211124_162107

Screenshot_20211124_162122

### CODE REVIEW

**Comment by MaxTru** [comment]
cc. @felix-mueller => could you please also have a final look from requester perspective?

**Comment by felix-mueller** [comment]
@MaxTru looks perfect. Thank you for your time

**Comment by andreasgeier** [comment]
Please ensure basic styling. Descriptions should have the same size as the labels (13px), links are blue and underlined.

```
p.description {
    color: var(--color-grey-225-10-35);
    font-size: 13px;
    line-height: 17px;
}
a {
    color: var(--color-blue-205-100-50);
    text-decoration: underline;
}
a:hover, a:active, a:focus {
    color: var(--color-blue-205-100-45);
    text-decoration: underline;
}
```

Screen Shot 2021-11-25 at 08 50 01

**Comment by MaxTru** [comment]
> Please ensure basic styling. Descriptions should have the same size as the labels (13px), links are blue and underlined.
> 
> ```
> p.description {
>     color: var(--color-grey-225-10-35);
>     font-size: 13px;
>     line-height: 17px;
> }
> a {
>     color: var(--color-blue-205-100-50);
>     text-decoration: underline;
> }
> a:hover, a:active, a:focus {
>     color: var(--color-blue-205-100-45);
>     text-decoration: underline;
> }
> ```
> 
> Screen Shot 2021-11-25 at 08 50 01

I don't think this is part of this PR?
This PR just adds the descriptions, but does not style changes.

**Review by andreasgeier — APPROVED** [review]
✅ Approved.

The styling issue is handled in bug #202

**Review by pinussilvestrus — APPROVED** [review]

**Pull request merged**
