### PR TITLE
85 camunda multiinstance props

### LINKED ISSUE #85: Camunda multi-instance props
requires #84

### PR DESCRIPTION
**Pull request by MaxTru**
depends on #86 

closes #85 

This adds camunda specific multiInstanceProps:
Screenshot_20210830_130725

### CODE REVIEW

**Comment by MaxTru** [comment]
Ready to be merged once #86 was merged

**Review by andreasgeier — APPROVED** [review]
✅ &nbsp; LGTM

**Comment by MaxTru** [comment]
ready for review and merge @pinussilvestrus or @barmac

**Review by pinussilvestrus — APPROVED** [review]
LGTM 👍

**Pull request merged**
