### PR TITLE
feat: remove unnecessary classes

### PR DESCRIPTION
**Pull request by barmac**
Related to https://github.com/bpmn-io/properties-panel/issues/45

Requires https://github.com/bpmn-io/properties-panel/pull/91

### CODE REVIEW

**Comment by barmac** [comment]
This should not change the look of the elements but their html:

image

**Comment by barmac** [comment]
Before:
image

**Comment by andreasgeier** [comment]
Please explain what is the goal of this PR.

**Comment by nikku** [comment]
This is a follow up to https://github.com/bpmn-io/properties-panel/pull/91 that performs necessary cleanups.

**Review by nikku — APPROVED** [review]
I can confirm it works as intended: 

capture 8CCuxK_optimized

Good job!

**Pull request merged**
