### PR TITLE
feat(element-templates): display description of custom properties

### LINKED ISSUE #167: Description for fields is missing
__Describe the Bug__

Description for fields is missing

__Steps to Reproduce__

1. Have this template and apply it:
```
{
    "$schema": "https://unpkg.com/@camunda/element-templates-json-schema@0.4.0/resources/schema.json",
    "name": "WS Caller Task",
    "id": "com.camunda.example.WsCaller",
    "description": "Requires the user to provide a Web Service URL.",
    "appliesTo": [
      "bpmn:ServiceTask"
    ],
    "properties": [
      {
        "label": "Web Service URL",
        "description": "Specify the url of the web service to talk to.",
        "type": "String",
        "binding": {
          "type": "camunda:property",
          "name": "webServiceUrl"
        },
        "constraints": {
          "notEmpty": true,
          "pattern": {
            "value": "^https://.*",
            "message": "Must be https URL."
          }
        }
      },
      {
        "type": "Hidden",
        "value": "com.camunda.example.WsCaller",
        "binding": {
          "type": "property",
          "name": "camunda:class"
        }
      }
    ]
  }
```
2.  ===> Notice that the description for the custom input is not displayed in the UI
`"description": "Specify the url of the web service to talk to."`

__Expected Behavior__

Description for inputs are shown in UI in accordance with template configuration.

__Environment__

https://github.com/bpmn-io/bpmn-properties-panel/pull/161

### PR DESCRIPTION
**Pull request by barmac**
image

Closes #167

### CODE REVIEW

**Comment by andreasgeier** [comment]
Didn't we agree to bundle everything into one artifact for design review and not conduct individual ones?

What I can see in the screenshot looks good but I would need to see a real-world example to assess all aspects, like line-height, for instance. Also, we have descriptions on other places such as variable descriptions for I/O.

**Comment by barmac** [comment]
> Didn't we agree to bundle everything into one artifact for design review and not conduct individual ones?
> 
> What I can see in the screenshot looks good but I would need to see a real-world example to assess all aspects, like line-height, for instance. Also, we have descriptions on other places such as variable descriptions for I/O.

I wasn't sure if it was only till the last demo or till we have a finished implementation of the whole epic. I'll remove the assignment then and thank you for the notice.

**Review by nikku — APPROVED** [review]
We did not expose this one to `npm run start:templates`, right? I think we should to complete our manual testing coverage.

Looks good to me. :+1:

**Comment by barmac** [comment]
> We did not expose this one to `npm run start:templates`, right? I think we should to complete our manual testing coverage.

I created an issue for this: https://github.com/bpmn-io/bpmn-properties-panel/issues/179

Thanks for the review!

**Pull request merged**
