### PR TITLE
fix(zeebe): timer events documentation links

### LINKED ISSUE #123: Timer event documentation link leads to "Page not found" for a brief period
Issue reference: https://github.com/camunda/camunda-modeler/issues/2413
Comment reference: @MaxTru  https://github.com/camunda/camunda-modeler/issues/2413#issuecomment-919068364

__Describe the Bug__

On clicking the documentation link in the timer event, for a short period "page not found" message is displayed until it is redirected to the actual documentation page.

__Steps to Reproduce__

1. In the Modeler, open a new BPMN diagram for cloud and add a timer event.
2. Open the properties panel and click on the field Timer event.
3. Now click open the link "documentation: Timer events"
4. We could see that for a very short period "page not found" is displayed until the actual documentation page is displayed.

__Expected Behavior__

On clicking the link it should directly lead to the documentation page without any error page popping up.

__Environment__

OS: [Windows 10]
Camunda Modeler Version: [4.10.0]
Execution Platform: [Camunda Cloud]

### PR DESCRIPTION
**Pull request by chincholikarsalil**
Closes #123 
Related to https://github.com/camunda/camunda-modeler/issues/2413

### CODE REVIEW

**Review by pinussilvestrus — COMMENTED** [review]
Thanks a lot for your contribution! It works like a charm 👍 One thing we should update before we can merge is the commit message. Let's make sure it references the correct issue, so something like

```sh
fix(zeebe): timer events documentation links

Closes #123 
Related to https://github.com/camunda/camunda-modeler/issues/2413
```

**Comment by chincholikarsalil** [comment]
Thanks a lot!
I have also updated the title accordingly.
Cheers!

**Comment by pinussilvestrus** [comment]
> Thanks a lot! I have also updated the title accordingly. Cheers!

The commit message still doesn't include the referencing issues: `fix: timer events link`.

Can you add them to the description?

**Comment by chincholikarsalil** [comment]
> The commit message still doesn't include the referencing issues: `fix: timer events link`.
> 
> Can you add them to the description?

Absolutely, I have changed the commit message now, please check.

**Review by pinussilvestrus — APPROVED** [review]

**Comment by pinussilvestrus** [comment]
Thank you a lot! Great contribution 🎉

**Pull request merged**
