### PR TITLE
chore: bump @bpmn-io/properties-panel to v0.4.1

### LINKED ISSUE #21: Executeable checkBox value change cannot be undone
__Describe the Bug__

Executeable checkBox value change cannot be undone.

__Steps to Reproduce__

1. Checkout https://github.com/bpmn-io/bpmn-properties-panel/commit/9e98cf089f2c303d76d8a21a5a50fd1f5df5df76 of this repo
2. Run `npm start`
3. Select the process
4. Set the `Executeable` checkbox in the General group
5. Keyboard input `CTRL + Z` for undo
6. ==> Nothing happends

__Expected Behavior__

Undo works for checkbox

__Environment__

- Host (Browser/Node version), if applicable: Chrome 91
- OS: Linux
- Library version: https://github.com/bpmn-io/bpmn-properties-panel/commit/9e98cf089f2c303d76d8a21a5a50fd1f5df5df76

### LINKED ISSUE #115: Properties Panel Becomes Partially Inaccessible
In some cases when there is not enough space on the screen the properties panel moves up and becomes partially inaccessible until the next render.

Before:

chrome_FQlK7Wh0ud

After:

chrome_3emKn3NRuZ

# Reproduce

1. Select a call activity
2. Add out mappings until the properties panel starts to scroll
3. Set _Propagate all variables_ to true
4. Properties panel moves up

Related to https://github.com/bpmn-io/bpmn-properties-panel/pull/94#issuecomment-921627378
Related to camunda/camunda-modeler#2364

### PR DESCRIPTION
**Pull request by MaxTru**
closes #115

---

closes #21
Peek 2021-09-24 09-13

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Let`s use `deps` for the commit message

```sh
deps: bump @bpmn-io/properties-panel to v0.4.1
```

**Comment by MaxTru** [comment]
> Let's use `deps` for the commit message
> 
> ```shell
> deps: bump @bpmn-io/properties-panel to v0.4.1
> ```

Sure :facepalm:

**Review by pinussilvestrus — COMMENTED** [review]
Looks good to me on Mac 👍  I'll keep it open for @philippfromme to verify on Windows.

**Comment by philippfromme** [comment]
> Looks good to me on Mac 👍 I'll keep it open for @philippfromme to verify on Windows.

Let me check that out.

**Review by philippfromme — APPROVED** [review]
👏🏻

**Pull request merged**
